package cppanalysis

import (
	"context"
	"crypto/sha256"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"

	gotreesitter "github.com/odvcencio/gotreesitter"

	"github.com/maxqstudio/DoctorCode/internal/detector"
	"github.com/maxqstudio/DoctorCode/internal/model"
)

const (
	ruleLogic    = "CPP-LOGIC-DUPLICATE-CONDITION"
	ruleSecurity = "CPP-SEC-HARDCODED-CREDENTIAL"
	ruleSimplify = "CPP-SIMPLIFY-BOOL-RETURN"
)

type Analyzer struct{}

type parsedFile struct {
	rel       string
	source    []byte
	document  *syntaxDocument
	generated bool
	ambiguous bool
}

func New() *Analyzer { return &Analyzer{} }

func (a *Analyzer) Name() string { return "cpp/gotreesitter-v1" }

func (a *Analyzer) Descriptor() detector.Descriptor {
	return detector.Descriptor{
		ID:         a.Name(),
		Language:   "C / C++",
		Extensions: []string{".c", ".cc", ".cpp", ".cxx"},
		Parser: detector.ParserContract{
			Kind:       detector.ParserEmbeddedAST,
			Provider:   "gotreesitter v0.55.1 C/C++",
			FailClosed: true,
		},
		Availability: detector.AvailabilityContract{Mode: detector.AvailabilitySourceOnly},
		EvidenceBoundary: "Pure-Go gotreesitter C/C++ syntax/AST authority. M24 is bounded to direct literal SECURITY, opposite-boolean SIMPLIFY, and duplicate unmodified bool/_Bool parameter LOGIC. Headers are not parsed as standalone source because their dialect is ambiguous without compilation context. Generated source, macro definitions, conditional preprocessing, pointer/reference bool parameters, non-bool parameters, mutation, unresolved type semantics, DEADCODE, BLOAT, safe autofix, and automatic deletion remain outside authority.",
		Rules: []detector.RuleMetadata{
			{ID: ruleLogic, Category: model.CategoryLogic, SafeAutofix: false},
			{ID: ruleSecurity, Category: model.CategorySecurity, SafeAutofix: false},
			{ID: ruleSimplify, Category: model.CategorySimplify, SafeAutofix: false},
		},
		Benchmark: detector.BenchmarkContract{SchemaVersion: 1, Languages: []string{"C / C++"}},
	}
}

func (a *Analyzer) Analyze(ctx context.Context, root string) ([]model.Finding, error) {
	files, err := parseSourceFiles(ctx, root)
	if err != nil {
		return nil, err
	}
	if len(files) == 0 {
		return nil, fmt.Errorf("%w: no C/C++ source files", detector.ErrUnavailable)
	}

	var findings []model.Finding
	for _, file := range files {
		if file.generated || file.ambiguous {
			continue
		}
		findings = append(findings, collectFindings(file)...)
	}
	return findings, nil
}

func parseSourceFiles(ctx context.Context, root string) ([]*parsedFile, error) {
	var paths []string
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if err := ctx.Err(); err != nil {
			return err
		}
		if entry.IsDir() {
			if path != root && ignoredDirectory(entry.Name()) {
				return filepath.SkipDir
			}
			return nil
		}
		if entry.Type()&fs.ModeSymlink != 0 {
			return nil
		}
		if _, ok := kindForExtension(filepath.Ext(path)); ok {
			paths = append(paths, path)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(paths)

	files := make([]*parsedFile, 0, len(paths))
	for _, path := range paths {
		kind, _ := kindForExtension(filepath.Ext(path))
		source, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read C/C++ source %s: %w", path, err)
		}
		if strings.IndexByte(string(source), 0) >= 0 {
			return nil, fmt.Errorf("C/C++ parse incomplete: %s contains NUL byte", path)
		}
		document, err := parseTranslationUnit(source, kind)
		if err != nil {
			return nil, fmt.Errorf("%s syntax validation failed for %s: %w", kind, path, err)
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return nil, err
		}
		files = append(files, &parsedFile{
			rel:       filepath.ToSlash(rel),
			source:    source,
			document:  document,
			generated: generatedSource(source),
			ambiguous: semanticPreprocessorAmbiguity(document),
		})
	}
	return files, nil
}

func kindForExtension(ext string) (sourceKind, bool) {
	switch strings.ToLower(ext) {
	case ".c":
		return sourceC, true
	case ".cc", ".cpp", ".cxx":
		return sourceCPP, true
	default:
		return "", false
	}
}

func ignoredDirectory(name string) bool {
	switch strings.ToLower(name) {
	case ".git", ".hg", ".svn", ".idea", ".vscode", "build", "target", "out", "dist", "coverage", "node_modules", "vendor", "generated", "generated-sources", "testdata":
		return true
	default:
		return false
	}
}

func generatedSource(source []byte) bool {
	limit := len(source)
	if limit > 1024 {
		limit = 1024
	}
	prefix := strings.ToLower(string(source[:limit]))
	for _, marker := range []string{"code generated", "generated by", "do not edit", "@generated"} {
		if strings.Contains(prefix, marker) {
			return true
		}
	}
	return false
}

func semanticPreprocessorAmbiguity(document *syntaxDocument) bool {
	ambiguous := false
	lang := document.language
	gotreesitter.Walk(document.tree.RootNode(), func(node *gotreesitter.Node, _ int) gotreesitter.WalkAction {
		kind := node.Type(lang)
		if strings.HasPrefix(kind, "preproc_") && kind != "preproc_include" {
			ambiguous = true
			return gotreesitter.WalkStop
		}
		return gotreesitter.WalkContinue
	})
	return ambiguous
}

func collectFindings(file *parsedFile) []model.Finding {
	var findings []model.Finding
	findings = append(findings, securityFindings(file)...)
	findings = append(findings, simplifyFindings(file)...)
	findings = append(findings, logicFindings(file)...)
	return findings
}

func securityFindings(file *parsedFile) []model.Finding {
	var out []model.Finding
	lang := file.document.language
	gotreesitter.Walk(file.document.tree.RootNode(), func(node *gotreesitter.Node, _ int) gotreesitter.WalkAction {
		if node.Type(lang) != "init_declarator" {
			return gotreesitter.WalkContinue
		}
		declarator := node.ChildByFieldName("declarator", lang)
		valueNode := node.ChildByFieldName("value", lang)
		nameNode := declaredIdentifier(declarator, lang)
		if nameNode == nil || valueNode == nil || valueNode.Type(lang) != "string_literal" {
			return gotreesitter.WalkContinue
		}
		name := nodeText(file.source, nameNode)
		if !credentialLike(name) {
			return gotreesitter.WalkContinue
		}
		value, ok := literalStringValue(file.source, valueNode)
		if !ok || obviousPlaceholder(value) {
			return gotreesitter.WalkContinue
		}
		digest := sha256.Sum256([]byte(value))
		out = append(out, newFinding(
			ruleSecurity,
			model.CategorySecurity,
			model.SeverityHigh,
			model.ConfidenceSuspicious,
			file.rel,
			1+int(node.StartPoint().Row),
			"credential-like C/C++ binding is assigned a hardcoded string literal",
			[]string{
				fmt.Sprintf("identifier=%s literal_bytes=%d sha256_prefix=%x", name, len(value), digest[:6]),
				"literal value is redacted",
			},
		))
		return gotreesitter.WalkSkipChildren
	})
	return out
}

func literalStringValue(source []byte, node *gotreesitter.Node) (string, bool) {
	if node == nil {
		return "", false
	}
	raw := strings.TrimSpace(nodeText(source, node))
	if len(raw) < 2 || raw[0] != '"' || raw[len(raw)-1] != '"' {
		return "", false
	}
	value, err := strconv.Unquote(raw)
	if err != nil {
		return "", false
	}
	return value, true
}

func declaredIdentifier(node *gotreesitter.Node, lang *gotreesitter.Language) *gotreesitter.Node {
	for node != nil {
		if node.Type(lang) == "identifier" {
			return node
		}
		next := node.ChildByFieldName("declarator", lang)
		if next == nil {
			return nil
		}
		node = next
	}
	return nil
}

func credentialLike(name string) bool {
	var normalized strings.Builder
	for _, r := range strings.ToLower(name) {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			normalized.WriteRune(r)
		}
	}
	value := normalized.String()
	for _, suffix := range []string{"password", "passwd", "secret", "apikey", "token", "privatekey", "accesskey"} {
		if value == suffix || strings.HasSuffix(value, suffix) {
			return true
		}
	}
	return false
}

func obviousPlaceholder(value string) bool {
	lower := strings.ToLower(strings.TrimSpace(value))
	if lower == "" || strings.HasPrefix(lower, "${") || strings.HasPrefix(lower, "$(") {
		return true
	}
	for _, marker := range []string{"example", "dummy", "placeholder", "changeme", "change-me", "notasecret", "not-a-secret", "your_", "your-", "<"} {
		if strings.Contains(lower, marker) {
			return true
		}
	}
	return false
}

func simplifyFindings(file *parsedFile) []model.Finding {
	var out []model.Finding
	lang := file.document.language
	gotreesitter.Walk(file.document.tree.RootNode(), func(fn *gotreesitter.Node, _ int) gotreesitter.WalkAction {
		if fn.Type(lang) != "function_definition" {
			return gotreesitter.WalkContinue
		}
		body := fn.ChildByFieldName("body", lang)
		if body == nil {
			return gotreesitter.WalkSkipChildren
		}
		params := unmodifiedBoolParameters(file, fn, body)
		if len(params) == 0 {
			return gotreesitter.WalkSkipChildren
		}
		gotreesitter.Walk(body, func(node *gotreesitter.Node, _ int) gotreesitter.WalkAction {
			if node != body && (node.Type(lang) == "function_definition" || node.Type(lang) == "lambda_expression") {
				return gotreesitter.WalkSkipChildren
			}
			if node.Type(lang) != "if_statement" {
				return gotreesitter.WalkContinue
			}
			if _, ok := directBoolCondition(file.source, node.ChildByFieldName("condition", lang), params); !ok {
				return gotreesitter.WalkContinue
			}
			left, leftOK := branchBoolean(file, node.ChildByFieldName("consequence", lang))
			right, rightOK := alternativeBoolean(file, node.ChildByFieldName("alternative", lang))
			if !leftOK || !rightOK || left == right {
				return gotreesitter.WalkContinue
			}
			out = append(out, newFinding(
				ruleSimplify,
				model.CategorySimplify,
				model.SeverityLow,
				model.ConfidenceHigh,
				file.rel,
				1+int(node.StartPoint().Row),
				"opposite C/C++ boolean return branches can be reduced to the condition or its negation",
				[]string{"AST-proven if/else branches each contain exactly one opposite boolean return", "condition is an unmodified bool/_Bool value parameter", "safe_autofix remains disabled"},
			))
			return gotreesitter.WalkSkipChildren
		})
		return gotreesitter.WalkSkipChildren
	})
	return out
}

func branchBoolean(file *parsedFile, node *gotreesitter.Node) (bool, bool) {
	if node == nil || node.Type(file.document.language) != "compound_statement" || node.NamedChildCount() != 1 {
		return false, false
	}
	return returnBoolean(file, node.NamedChild(0))
}

func alternativeBoolean(file *parsedFile, node *gotreesitter.Node) (bool, bool) {
	lang := file.document.language
	if node == nil || node.Type(lang) != "else_clause" || node.NamedChildCount() != 1 {
		return false, false
	}
	return branchBoolean(file, node.NamedChild(0))
}

func returnBoolean(file *parsedFile, node *gotreesitter.Node) (bool, bool) {
	lang := file.document.language
	if node == nil || node.Type(lang) != "return_statement" || node.NamedChildCount() != 1 {
		return false, false
	}
	value := strings.TrimSpace(nodeText(file.source, node.NamedChild(0)))
	if file.document.kind == sourceC {
		switch value {
		case "1":
			return true, true
		case "0":
			return false, true
		default:
			return false, false
		}
	}
	switch value {
	case "true":
		return true, true
	case "false":
		return false, true
	default:
		return false, false
	}
}

func logicFindings(file *parsedFile) []model.Finding {
	var out []model.Finding
	lang := file.document.language
	gotreesitter.Walk(file.document.tree.RootNode(), func(fn *gotreesitter.Node, _ int) gotreesitter.WalkAction {
		if fn.Type(lang) != "function_definition" {
			return gotreesitter.WalkContinue
		}
		body := fn.ChildByFieldName("body", lang)
		if body == nil {
			return gotreesitter.WalkSkipChildren
		}
		params := unmodifiedBoolParameters(file, fn, body)
		if len(params) == 0 {
			return gotreesitter.WalkSkipChildren
		}
		continuations := map[uint32]bool{}
		gotreesitter.Walk(body, func(node *gotreesitter.Node, _ int) gotreesitter.WalkAction {
			if node != body && (node.Type(lang) == "function_definition" || node.Type(lang) == "lambda_expression") {
				return gotreesitter.WalkSkipChildren
			}
			if node.Type(lang) != "if_statement" || continuations[node.StartByte()] {
				return gotreesitter.WalkContinue
			}
			chain := ifChain(node, lang)
			for i := 1; i < len(chain); i++ {
				continuations[chain[i].StartByte()] = true
			}
			seen := map[string]int{}
			for _, item := range chain {
				key, ok := directBoolCondition(file.source, item.ChildByFieldName("condition", lang), params)
				if !ok {
					seen = map[string]int{}
					continue
				}
				line := 1 + int(item.StartPoint().Row)
				if earlier, exists := seen[key]; exists {
					out = append(out, newFinding(
						ruleLogic,
						model.CategoryLogic,
						model.SeverityMedium,
						model.ConfidenceHigh,
						file.rel,
						line,
						"duplicate side-effect-free C/C++ bool-parameter condition appears later in the same if/else-if chain",
						[]string{fmt.Sprintf("AST-proven same unmodified bool/_Bool parameter condition already appeared at line %d", earlier), "unsupported or side-effect-capable conditions are proof barriers"},
					))
					continue
				}
				seen[key] = line
			}
			return gotreesitter.WalkSkipChildren
		})
		return gotreesitter.WalkSkipChildren
	})
	return out
}

func ifChain(node *gotreesitter.Node, lang *gotreesitter.Language) []*gotreesitter.Node {
	chain := []*gotreesitter.Node{node}
	current := node
	for {
		alternative := current.ChildByFieldName("alternative", lang)
		if alternative == nil || alternative.Type(lang) != "else_clause" || alternative.NamedChildCount() != 1 {
			break
		}
		next := alternative.NamedChild(0)
		if next == nil || next.Type(lang) != "if_statement" {
			break
		}
		chain = append(chain, next)
		current = next
	}
	return chain
}

func unmodifiedBoolParameters(file *parsedFile, fn, body *gotreesitter.Node) map[string]bool {
	params := boolParameters(file, fn)
	for name := range params {
		if parameterMutatedOrShadowed(file, body, name) {
			delete(params, name)
		}
	}
	return params
}

func boolParameters(file *parsedFile, fn *gotreesitter.Node) map[string]bool {
	lang := file.document.language
	out := map[string]bool{}
	declarator := fn.ChildByFieldName("declarator", lang)
	for declarator != nil && declarator.Type(lang) != "function_declarator" {
		declarator = declarator.ChildByFieldName("declarator", lang)
	}
	if declarator == nil {
		return out
	}
	parameters := declarator.ChildByFieldName("parameters", lang)
	if parameters == nil {
		return out
	}
	for i := uint32(0); i < parameters.NamedChildCount(); i++ {
		parameter := parameters.NamedChild(i)
		if parameter == nil || parameter.Type(lang) != "parameter_declaration" {
			continue
		}
		typeNode := parameter.ChildByFieldName("type", lang)
		nameNode := parameter.ChildByFieldName("declarator", lang)
		if typeNode == nil || nameNode == nil || nameNode.Type(lang) != "identifier" {
			continue
		}
		typeText := strings.TrimSpace(nodeText(file.source, typeNode))
		if (file.document.kind == sourceC && typeText != "_Bool") || (file.document.kind == sourceCPP && typeText != "bool") {
			continue
		}
		out[nodeText(file.source, nameNode)] = true
	}
	return out
}

func parameterMutatedOrShadowed(file *parsedFile, body *gotreesitter.Node, name string) bool {
	mutated := false
	lang := file.document.language
	gotreesitter.Walk(body, func(node *gotreesitter.Node, _ int) gotreesitter.WalkAction {
		if mutated {
			return gotreesitter.WalkStop
		}
		if node != body && (node.Type(lang) == "function_definition" || node.Type(lang) == "lambda_expression") {
			return gotreesitter.WalkSkipChildren
		}
		switch node.Type(lang) {
		case "assignment_expression":
			left := node.ChildByFieldName("left", lang)
			if left != nil && left.Type(lang) == "identifier" && nodeText(file.source, left) == name {
				mutated = true
				return gotreesitter.WalkStop
			}
		case "update_expression":
			if containsDirectIdentifier(file.source, node, lang, name) {
				mutated = true
				return gotreesitter.WalkStop
			}
		case "init_declarator":
			decl := node.ChildByFieldName("declarator", lang)
			if decl != nil && decl.Type(lang) == "identifier" && nodeText(file.source, decl) == name {
				mutated = true
				return gotreesitter.WalkStop
			}
		}
		return gotreesitter.WalkContinue
	})
	return mutated
}

func containsDirectIdentifier(source []byte, node *gotreesitter.Node, lang *gotreesitter.Language, name string) bool {
	for i := uint32(0); i < node.NamedChildCount(); i++ {
		child := node.NamedChild(i)
		if child != nil && child.Type(lang) == "identifier" && nodeText(source, child) == name {
			return true
		}
	}
	return false
}

func directBoolCondition(source []byte, node *gotreesitter.Node, params map[string]bool) (string, bool) {
	if node == nil {
		return "", false
	}
	text := strings.TrimSpace(nodeText(source, node))
	for len(text) >= 2 && text[0] == '(' && text[len(text)-1] == ')' {
		text = strings.TrimSpace(text[1 : len(text)-1])
	}
	if params[text] {
		return text, true
	}
	if strings.HasPrefix(text, "!") {
		name := strings.TrimSpace(strings.TrimPrefix(text, "!"))
		if params[name] {
			return "!" + name, true
		}
	}
	return "", false
}

func nodeText(source []byte, node *gotreesitter.Node) string {
	if node == nil {
		return ""
	}
	start := int(node.StartByte())
	end := int(node.EndByte())
	if start < 0 || start > len(source) || end < start {
		return ""
	}
	if end > len(source) {
		end = len(source)
	}
	return string(source[start:end])
}

func newFinding(rule string, category model.Category, severity model.Severity, confidence model.Confidence, path string, line int, summary string, evidence []string) model.Finding {
	return model.Finding{
		ID:           detector.FindingID(rule, path, line, summary),
		RuleID:       rule,
		Category:     category,
		Severity:     severity,
		Confidence:   confidence,
		Path:         path,
		LineStart:    line,
		LineEnd:      line,
		Summary:      summary,
		Evidence:     evidence,
		Verification: []string{"compile with the repository C/C++ toolchain", "run repository tests"},
		SafeAutofix:  false,
	}
}
