package csharpanalysis

import (
	"context"
	"crypto/sha256"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"

	gotreesitter "github.com/odvcencio/gotreesitter"

	"github.com/maxqstudio/DoctorCode/internal/detector"
	"github.com/maxqstudio/DoctorCode/internal/model"
)

const (
	ruleLogic    = "CSHARP-LOGIC-DUPLICATE-CONDITION"
	ruleSecurity = "CSHARP-SEC-HARDCODED-CREDENTIAL"
	ruleSimplify = "CSHARP-SIMPLIFY-BOOL-RETURN"
)

type Analyzer struct{}

type parsedFile struct {
	rel       string
	source    []byte
	document  *syntaxDocument
	generated bool
	ambiguous bool
}

func New() *Analyzer { return &Analyzer{} }

func (a *Analyzer) Name() string { return "csharp/gotreesitter-v1" }

func (a *Analyzer) Descriptor() detector.Descriptor {
	return detector.Descriptor{
		ID:         a.Name(),
		Language:   "C#",
		Extensions: []string{".cs"},
		Parser: detector.ParserContract{
			Kind:       detector.ParserEmbeddedAST,
			Provider:   "gotreesitter v0.55.1 C#",
			FailClosed: true,
		},
		Availability: detector.AvailabilityContract{Mode: detector.AvailabilitySourceOnly},
		EvidenceBoundary: "Pure-Go gotreesitter C# syntax/AST authority. M25 is bounded to direct literal SECURITY, opposite-boolean SIMPLIFY, and duplicate unmodified bool parameter LOGIC. Generated source, conditional preprocessing, interpolation, placeholder credentials, local-function bodies, parameter mutation, cross-partial-type semantics, unresolved type semantics, DEADCODE, BLOAT, safe autofix, and automatic deletion remain outside authority.",
		Rules: []detector.RuleMetadata{
			{ID: ruleLogic, Category: model.CategoryLogic, SafeAutofix: false},
			{ID: ruleSecurity, Category: model.CategorySecurity, SafeAutofix: false},
			{ID: ruleSimplify, Category: model.CategorySimplify, SafeAutofix: false},
		},
		Benchmark: detector.BenchmarkContract{SchemaVersion: 1, Languages: []string{"C#"}},
	}
}

func (a *Analyzer) Analyze(ctx context.Context, root string) ([]model.Finding, error) {
	files, err := parseSourceFiles(ctx, root)
	if err != nil {
		return nil, err
	}
	if len(files) == 0 {
		return nil, fmt.Errorf("%w: no C# source files", detector.ErrUnavailable)
	}

	var findings []model.Finding
	for _, file := range files {
		if file.generated || file.ambiguous {
			continue
		}
		findings = append(findings, collectFindings(file)...)
	}
	return findings, nil
}

func parseSourceFiles(ctx context.Context, root string) ([]*parsedFile, error) {
	var paths []string
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if err := ctx.Err(); err != nil {
			return err
		}
		if entry.IsDir() {
			if path != root && ignoredDirectory(entry.Name()) {
				return filepath.SkipDir
			}
			return nil
		}
		if entry.Type()&fs.ModeSymlink != 0 {
			return nil
		}
		if strings.EqualFold(filepath.Ext(path), ".cs") {
			paths = append(paths, path)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(paths)

	files := make([]*parsedFile, 0, len(paths))
	for _, path := range paths {
		source, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read C# source %s: %w", path, err)
		}
		if strings.IndexByte(string(source), 0) >= 0 {
			return nil, fmt.Errorf("C# parse incomplete: %s contains NUL byte", path)
		}
		document, err := parseSyntax(source)
		if err != nil {
			return nil, fmt.Errorf("C# syntax validation failed for %s: %w", path, err)
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return nil, err
		}
		files = append(files, &parsedFile{
			rel:       filepath.ToSlash(rel),
			source:    source,
			document:  document,
			generated: generatedSource(source),
			ambiguous: semanticPreprocessorAmbiguity(document),
		})
	}
	return files, nil
}

func ignoredDirectory(name string) bool {
	switch strings.ToLower(name) {
	case ".git", ".hg", ".svn", ".idea", ".vscode", "bin", "obj", "build", "target", "out", "dist", "coverage", "node_modules", "vendor", "generated", "generated-sources", "testdata":
		return true
	default:
		return false
	}
}

func generatedSource(source []byte) bool {
	limit := len(source)
	if limit > 1024 {
		limit = 1024
	}
	prefix := strings.ToLower(string(source[:limit]))
	for _, marker := range []string{"<auto-generated", "code generated", "generated by", "do not edit", "@generated"} {
		if strings.Contains(prefix, marker) {
			return true
		}
	}
	return false
}

func semanticPreprocessorAmbiguity(document *syntaxDocument) bool {
	ambiguous := false
	lang := document.language
	gotreesitter.Walk(document.tree.RootNode(), func(node *gotreesitter.Node, _ int) gotreesitter.WalkAction {
		kind := node.Type(lang)
		if strings.HasPrefix(kind, "preproc_") || strings.HasPrefix(kind, "preprocessor_") {
			ambiguous = true
			return gotreesitter.WalkStop
		}
		return gotreesitter.WalkContinue
	})
	return ambiguous
}

func collectFindings(file *parsedFile) []model.Finding {
	var findings []model.Finding
	findings = append(findings, securityFindings(file)...)
	findings = append(findings, simplifyFindings(file)...)
	findings = append(findings, logicFindings(file)...)
	return findings
}

func securityFindings(file *parsedFile) []model.Finding {
	var out []model.Finding
	lang := file.document.language
	gotreesitter.Walk(file.document.tree.RootNode(), func(node *gotreesitter.Node, _ int) gotreesitter.WalkAction {
		if node.Type(lang) != "variable_declarator" {
			return gotreesitter.WalkContinue
		}
		nameNode := node.ChildByFieldName("name", lang)
		valueNode := node.ChildByFieldName("value", lang)
		if nameNode == nil || valueNode == nil || valueNode.Type(lang) != "string_literal" {
			return gotreesitter.WalkContinue
		}
		name := strings.TrimSpace(nodeText(file.source, nameNode))
		if !credentialLike(name) {
			return gotreesitter.WalkContinue
		}
		value, ok := literalStringValue(file.source, valueNode)
		if !ok || obviousPlaceholder(value) {
			return gotreesitter.WalkContinue
		}
		digest := sha256.Sum256([]byte(value))
		out = append(out, newFinding(
			ruleSecurity,
			model.CategorySecurity,
			model.SeverityHigh,
			model.ConfidenceSuspicious,
			file.rel,
			1+int(node.StartPoint().Row),
			"credential-like C# binding is assigned a hardcoded string literal",
			[]string{
				fmt.Sprintf("identifier=%s literal_bytes=%d sha256_prefix=%x", name, len(value), digest[:6]),
				"literal value is redacted",
			},
		))
		return gotreesitter.WalkSkipChildren
	})
	return out
}

func literalStringValue(source []byte, node *gotreesitter.Node) (string, bool) {
	if node == nil {
		return "", false
	}
	raw := strings.TrimSpace(nodeText(source, node))
	if len(raw) < 2 || raw[0] != '"' || raw[len(raw)-1] != '"' {
		return "", false
	}
	value, err := strconv.Unquote(raw)
	if err != nil {
		return "", false
	}
	return value, true
}

func credentialLike(name string) bool {
	var normalized strings.Builder
	for _, r := range strings.ToLower(name) {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			normalized.WriteRune(r)
		}
	}
	value := normalized.String()
	for _, suffix := range []string{"password", "passwd", "secret", "apikey", "token", "privatekey", "accesskey"} {
		if value == suffix || strings.HasSuffix(value, suffix) {
			return true
		}
	}
	return false
}

func obviousPlaceholder(value string) bool {
	lower := strings.ToLower(strings.TrimSpace(value))
	if lower == "" || strings.HasPrefix(lower, "${") || strings.HasPrefix(lower, "$(") {
		return true
	}
	for _, marker := range []string{"example", "dummy", "placeholder", "changeme", "change-me", "notasecret", "not-a-secret", "your_", "your-", "<"} {
		if strings.Contains(lower, marker) {
			return true
		}
	}
	return false
}

func simplifyFindings(file *parsedFile) []model.Finding {
	var out []model.Finding
	lang := file.document.language
	gotreesitter.Walk(file.document.tree.RootNode(), func(method *gotreesitter.Node, _ int) gotreesitter.WalkAction {
		if method.Type(lang) != "method_declaration" {
			return gotreesitter.WalkContinue
		}
		body := methodBody(method, lang)
		if body == nil {
			return gotreesitter.WalkSkipChildren
		}
		params := unmodifiedBoolParameters(file, method, body)
		if len(params) == 0 {
			return gotreesitter.WalkSkipChildren
		}
		gotreesitter.Walk(body, func(node *gotreesitter.Node, _ int) gotreesitter.WalkAction {
			if node != body && nestedCallable(node.Type(lang)) {
				return gotreesitter.WalkSkipChildren
			}
			if node.Type(lang) != "if_statement" {
				return gotreesitter.WalkContinue
			}
			if _, ok := directBoolCondition(file, node.ChildByFieldName("condition", lang), params); !ok {
				return gotreesitter.WalkContinue
			}
			left, leftOK := branchBoolean(file, node.ChildByFieldName("consequence", lang))
			right, rightOK := branchBoolean(file, node.ChildByFieldName("alternative", lang))
			if !leftOK || !rightOK || left == right {
				return gotreesitter.WalkContinue
			}
			out = append(out, newFinding(
				ruleSimplify,
				model.CategorySimplify,
				model.SeverityLow,
				model.ConfidenceHigh,
				file.rel,
				1+int(node.StartPoint().Row),
				"opposite C# boolean return branches can be reduced to the condition or its negation",
				[]string{"AST-proven if/else branches each contain exactly one opposite boolean return", "condition is an unmodified bool value parameter", "safe_autofix remains disabled"},
			))
			return gotreesitter.WalkSkipChildren
		})
		return gotreesitter.WalkSkipChildren
	})
	return out
}

func logicFindings(file *parsedFile) []model.Finding {
	var out []model.Finding
	lang := file.document.language
	gotreesitter.Walk(file.document.tree.RootNode(), func(method *gotreesitter.Node, _ int) gotreesitter.WalkAction {
		if method.Type(lang) != "method_declaration" {
			return gotreesitter.WalkContinue
		}
		body := methodBody(method, lang)
		if body == nil {
			return gotreesitter.WalkSkipChildren
		}
		params := unmodifiedBoolParameters(file, method, body)
		if len(params) == 0 {
			return gotreesitter.WalkSkipChildren
		}
		gotreesitter.Walk(body, func(node *gotreesitter.Node, _ int) gotreesitter.WalkAction {
			if node != body && nestedCallable(node.Type(lang)) {
				return gotreesitter.WalkSkipChildren
			}
			if node.Type(lang) != "if_statement" {
				return gotreesitter.WalkContinue
			}
			name, ok := directBoolCondition(file, node.ChildByFieldName("condition", lang), params)
			if !ok {
				return gotreesitter.WalkContinue
			}
			alternative := node.ChildByFieldName("alternative", lang)
			if alternative == nil || alternative.Type(lang) != "if_statement" {
				return gotreesitter.WalkContinue
			}
			other, ok := directBoolCondition(file, alternative.ChildByFieldName("condition", lang), params)
			if !ok || other != name {
				return gotreesitter.WalkContinue
			}
			out = append(out, newFinding(
				ruleLogic,
				model.CategoryLogic,
				model.SeverityMedium,
				model.ConfidenceHigh,
				file.rel,
				1+int(alternative.StartPoint().Row),
				"C# else-if repeats the same unmodified boolean condition",
				[]string{"AST-proven consecutive if/else-if conditions reference the same bool parameter", "parameter is not assigned within the method body"},
			))
			return gotreesitter.WalkSkipChildren
		})
		return gotreesitter.WalkSkipChildren
	})
	return out
}

func methodBody(method *gotreesitter.Node, lang *gotreesitter.Language) *gotreesitter.Node {
	if method == nil {
		return nil
	}
	if body := method.ChildByFieldName("body", lang); body != nil && body.Type(lang) == "block" {
		return body
	}
	for i := 0; i < method.NamedChildCount(); i++ {
		child := method.NamedChild(i)
		if child != nil && child.Type(lang) == "block" {
			return child
		}
	}
	return nil
}

func unmodifiedBoolParameters(file *parsedFile, method, body *gotreesitter.Node) map[string]bool {
	lang := file.document.language
	paramsNode := method.ChildByFieldName("parameters", lang)
	if paramsNode == nil {
		for i := 0; i < method.NamedChildCount(); i++ {
			child := method.NamedChild(i)
			if child != nil && child.Type(lang) == "parameter_list" {
				paramsNode = child
				break
			}
		}
	}
	if paramsNode == nil {
		return nil
	}

	params := map[string]bool{}
	gotreesitter.Walk(paramsNode, func(node *gotreesitter.Node, _ int) gotreesitter.WalkAction {
		if node.Type(lang) != "parameter" {
			return gotreesitter.WalkContinue
		}
		typeNode := node.ChildByFieldName("type", lang)
		nameNode := node.ChildByFieldName("name", lang)
		if typeNode == nil || nameNode == nil || strings.TrimSpace(nodeText(file.source, typeNode)) != "bool" {
			return gotreesitter.WalkSkipChildren
		}
		name := strings.TrimSpace(nodeText(file.source, nameNode))
		if name != "" {
			params[name] = true
		}
		return gotreesitter.WalkSkipChildren
	})
	if len(params) == 0 {
		return nil
	}

	gotreesitter.Walk(body, func(node *gotreesitter.Node, _ int) gotreesitter.WalkAction {
		if node != body && nestedCallable(node.Type(lang)) {
			return gotreesitter.WalkSkipChildren
		}
		if node.Type(lang) != "assignment_expression" {
			return gotreesitter.WalkContinue
		}
		left := node.ChildByFieldName("left", lang)
		if left == nil {
			return gotreesitter.WalkContinue
		}
		name := strings.TrimSpace(nodeText(file.source, left))
		if params[name] {
			delete(params, name)
		}
		return gotreesitter.WalkContinue
	})
	return params
}

func nestedCallable(kind string) bool {
	switch kind {
	case "local_function_statement", "lambda_expression", "anonymous_method_expression":
		return true
	default:
		return false
	}
}

func directBoolCondition(file *parsedFile, node *gotreesitter.Node, params map[string]bool) (string, bool) {
	if node == nil {
		return "", false
	}
	name := strings.TrimSpace(nodeText(file.source, node))
	if !params[name] {
		return "", false
	}
	if node.Type(file.document.language) != "identifier" {
		return "", false
	}
	return name, true
}

func branchBoolean(file *parsedFile, node *gotreesitter.Node) (bool, bool) {
	if node == nil {
		return false, false
	}
	lang := file.document.language
	if node.Type(lang) != "block" || node.NamedChildCount() != 1 {
		return false, false
	}
	statement := node.NamedChild(0)
	if statement == nil || statement.Type(lang) != "return_statement" || statement.NamedChildCount() != 1 {
		return false, false
	}
	value := statement.NamedChild(0)
	if value == nil {
		return false, false
	}
	switch strings.TrimSpace(nodeText(file.source, value)) {
	case "true":
		return true, true
	case "false":
		return false, true
	default:
		return false, false
	}
}

func nodeText(source []byte, node *gotreesitter.Node) string {
	if node == nil {
		return ""
	}
	start := int(node.StartByte())
	end := int(node.EndByte())
	if start < 0 || end < start || start >= len(source) {
		return ""
	}
	if end > len(source) {
		end = len(source)
	}
	return string(source[start:end])
}

func newFinding(rule string, category model.Category, severity model.Severity, confidence model.Confidence, path string, line int, summary string, evidence []string) model.Finding {
	return model.Finding{
		ID:           detector.FindingID(rule, path, line, summary),
		RuleID:       rule,
		Category:     category,
		Severity:     severity,
		Confidence:   confidence,
		Path:         path,
		LineStart:    line,
		LineEnd:      line,
		Summary:      summary,
		Evidence:     evidence,
		Verification: []string{"compile with the repository C#/.NET toolchain", "run repository tests"},
		SafeAutofix:  false,
	}
}
